name              "glog"
maintainer        "ADADA, LLC"
maintainer_email  "chef@adadabase.com"
license           "MIT"
description       "Installs gflags."
version           "0.1"
long_description  "Installs gflags."
